### ISSUE TITLE
Request for Assistance: Seeking Information on Completed Chapters

### ISSUE THREAD

**Issue by toshmukhamedov** [rust-lang-uz/i10n#7]
I am interested in contributing to the project and making a positive impact through my efforts. However, I am currently facing a challenge in determining which chapters have been completed and require no further attention.
I kindly request your assistance in providing clarification regarding the completed chapters. Having an up-to-date list of the chapters that have already been addressed by other contributors would greatly help me focus my efforts effectively and avoid redundant work.
I understand that managing such a project can be intricate, and I genuinely appreciate the hard work and dedication of the project maintainers. By enhancing transparency in this aspect, we can foster a more collaborative and efficient environment for all contributors.
Thank you for your attention and support.

**Comment by orzklv** [comment]
@toshmukhamedov  Mostly, we discuss everything at our telegram chat: https://t.me/rustlanguz. Feel free to join us and contribute to our uzbek rust community!
